# Generated by Django 5.2.6 on 2025-09-12 10:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-createdat']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-createdat']},
        ),
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-createdat']},
        ),
        migrations.AlterModelOptions(
            name='riderequest',
            options={'ordering': ['-createdat']},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='read',
            new_name='isread',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymentdate',
            new_name='createdat',
        ),
        migrations.RemoveField(
            model_name='driververification',
            name='document',
        ),
        migrations.RemoveField(
            model_name='driververification',
            name='id',
        ),
        migrations.RemoveField(
            model_name='driververification',
            name='reviewedat',
        ),
        migrations.RemoveField(
            model_name='driververification',
            name='submittedat',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='driververification',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driververification',
            name='licenseurl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driververification',
            name='rcurl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentmethod',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='ride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='APP.ride'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transactionid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='requestedseats',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='user',
            name='govidurl',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver'), ('admin', 'Admin')], default='passenger', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicleregnumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicletype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driververification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='ridetype',
            field=models.CharField(choices=[('solo', 'Solo'), ('shared', 'Shared')], default='shared', max_length=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='seats',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_rides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='APP.ride'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='vehicledetails',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='riderequest',
            unique_together={('ride', 'passenger')},
        ),
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('pickupdate', models.DateField()),
                ('pickuptime', models.TimeField()),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Driver Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('estimatedfare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hires', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdat'],
            },
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travellers', to='APP.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripdate', models.DateField()),
                ('distance', models.PositiveIntegerField(help_text='Distance in kilometers')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_history', to='APP.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trip histories',
                'ordering': ['-tripdate'],
            },
        ),
    ]
